DISTRO = "freertos"
DISTRO_NAME = "FreeRTOS"
DISTRO_VERSION = "1.0"

TCLIBC = "newlib"

#INHIBIT_SYSROOT_STRIP="1"

INHERIT += "uninative"
require conf/distro/include/yocto-uninative.inc

# We're building baremetal, we dont need the default DISTRO_FEATURES from oe-core/poky
DISTRO_FEATURES_OPTED_OUT = "3g acl alsa bluetooth debuginfod ext2 gobject-introspection-data ipv4 ipv6 multiarch nfc nfs opengl pci ptest pulseaudio seccomp vfat vulkan wayland wifi x11 xattr zeroconf"